#
# dotphiles : https://github.com/dotphiles/dotphiles
#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#   Ben O'Hara <bohara@gmail.com>
#

# Customize to your needs...

source ~/.xsh
source /usr/share/chruby/chruby.sh

for rbversion in $(ls ~/.gem/ruby/)
do
    PATH=~/.gem/ruby/$rbversion/bin:$PATH
done
export PATH=$PATH