# -*- mode: shell-script -*-
#
# dotphiles : https://github.com/dotphiles/dotphiles
#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#   Ben O'Hara <bohara@gmail.com>
#

# Customize to your needs...

source ~/.xsh

ssh-add -L &> /dev/null
if [ $? -eq 0 ]
then
    echo 'Identities loaded'
else
    ssh-add ~/.ssh/{id_rsa,odl_app,odl_rsa} &> /dev/null
fi

alias edit="emacsclient -t $@"
alias newpw='copyq add "$(openssl rand -base64 32)"'
alias fix-ext-display="rm -i ~/local/share/kscreen/*"

[[ -s $HOME/.pythonz/etc/bashrc  ]] && source $HOME/.pythonz/etc/bashrc

mypath=$PATH
for pathname in $(ls ~/.pythonz/pythons/);
do
    export PATH="$PATH:/home/tmacey/.pythonz/pythons/$pathname/bin"
done
