#
# dotphiles : https://github.com/dotphiles/dotphiles
#
# Defines environment variables.
#
# Authors:
#   Ben O'Hara <bohara@gmail.com>
#

# Dont read global configs
unsetopt GLOBAL_RCS

# Set the path to dotzsh.
export DOTZSH="$HOME/.zsh"

# Source environment settings
source "$DOTZSH/env.zsh"

# Customize to your needs...

export EDITOR='/usr/local/bin/emacsclient -c -t -a emacs'
export VISUAL='/usr/local/bin/emacsclient -c -a emacs'
export PAGER='less -i'
export VAGRANT_DEFAULT_PROVIDER='libvirt'
